export const BIBLE_BOOKS = [
  { name: "Genesis", chapters: 50, testament: "OT", words: 38267 },
  { name: "Exodus", chapters: 40, testament: "OT", words: 32692 },
  { name: "Leviticus", chapters: 27, testament: "OT", words: 24546 },
  { name: "Numbers", chapters: 36, testament: "OT", words: 32902 },
  { name: "Deuteronomy", chapters: 34, testament: "OT", words: 28461 },
  { name: "Joshua", chapters: 24, testament: "OT", words: 18858 },
  { name: "Judges", chapters: 21, testament: "OT", words: 18976 },
  { name: "Ruth", chapters: 4, testament: "OT", words: 2578 },
  { name: "1 Samuel", chapters: 31, testament: "OT", words: 25061 },
  { name: "2 Samuel", chapters: 24, testament: "OT", words: 20612 },
  { name: "1 Kings", chapters: 22, testament: "OT", words: 24524 },
  { name: "2 Kings", chapters: 25, testament: "OT", words: 23532 },
  { name: "1 Chronicles", chapters: 29, testament: "OT", words: 20369 },
  { name: "2 Chronicles", chapters: 36, testament: "OT", words: 26074 },
  { name: "Ezra", chapters: 10, testament: "OT", words: 7441 },
  { name: "Nehemiah", chapters: 13, testament: "OT", words: 10483 },
  { name: "Esther", chapters: 10, testament: "OT", words: 5637 },
  { name: "Job", chapters: 42, testament: "OT", words: 10102 },
  { name: "Psalms", chapters: 150, testament: "OT", words: 43743 },
  { name: "Proverbs", chapters: 31, testament: "OT", words: 15043 },
  { name: "Ecclesiastes", chapters: 12, testament: "OT", words: 5584 },
  { name: "Song of Solomon", chapters: 8, testament: "OT", words: 2661 },
  { name: "Isaiah", chapters: 66, testament: "OT", words: 37044 },
  { name: "Jeremiah", chapters: 52, testament: "OT", words: 42659 },
  { name: "Lamentations", chapters: 5, testament: "OT", words: 3415 },
  { name: "Ezekiel", chapters: 48, testament: "OT", words: 39407 },
  { name: "Daniel", chapters: 12, testament: "OT", words: 11606 },
  { name: "Hosea", chapters: 14, testament: "OT", words: 5175 },
  { name: "Joel", chapters: 3, testament: "OT", words: 2034 },
  { name: "Amos", chapters: 9, testament: "OT", words: 4217 },
  { name: "Obadiah", chapters: 1, testament: "OT", words: 670 },
  { name: "Jonah", chapters: 4, testament: "OT", words: 1321 },
  { name: "Micah", chapters: 7, testament: "OT", words: 3153 },
  { name: "Nahum", chapters: 3, testament: "OT", words: 1285 },
  { name: "Habakkuk", chapters: 3, testament: "OT", words: 1476 },
  { name: "Zephaniah", chapters: 3, testament: "OT", words: 1617 },
  { name: "Haggai", chapters: 2, testament: "OT", words: 1131 },
  { name: "Zechariah", chapters: 14, testament: "OT", words: 6444 },
  { name: "Malachi", chapters: 4, testament: "OT", words: 1782 },
  { name: "Matthew", chapters: 28, testament: "NT", words: 23684 },
  { name: "Mark", chapters: 16, testament: "NT", words: 15171 },
  { name: "Luke", chapters: 24, testament: "NT", words: 25944 },
  { name: "John", chapters: 21, testament: "NT", words: 19099 },
  { name: "Acts", chapters: 28, testament: "NT", words: 24250 },
  { name: "Romans", chapters: 16, testament: "NT", words: 9447 },
  { name: "1 Corinthians", chapters: 16, testament: "NT", words: 9489 },
  { name: "2 Corinthians", chapters: 13, testament: "NT", words: 6092 },
  { name: "Galatians", chapters: 6, testament: "NT", words: 3098 },
  { name: "Ephesians", chapters: 6, testament: "NT", words: 3030 },
  { name: "Philippians", chapters: 4, testament: "NT", words: 2002 },
  { name: "Colossians", chapters: 4, testament: "NT", words: 1998 },
  { name: "1 Thessalonians", chapters: 5, testament: "NT", words: 1857 },
  { name: "2 Thessalonians", chapters: 3, testament: "NT", words: 1042 },
  { name: "1 Timothy", chapters: 6, testament: "NT", words: 2269 },
  { name: "2 Timothy", chapters: 4, testament: "NT", words: 1703 },
  { name: "Titus", chapters: 3, testament: "NT", words: 921 },
  { name: "Philemon", chapters: 1, testament: "NT", words: 445 },
  { name: "Hebrews", chapters: 13, testament: "NT", words: 6913 },
  { name: "James", chapters: 5, testament: "NT", words: 2309 },
  { name: "1 Peter", chapters: 5, testament: "NT", words: 2767 },
  { name: "2 Peter", chapters: 3, testament: "NT", words: 1099 },
  { name: "1 John", chapters: 5, testament: "NT", words: 2523 },
  { name: "2 John", chapters: 1, testament: "NT", words: 245 },
  { name: "3 John", chapters: 1, testament: "NT", words: 219 },
  { name: "Jude", chapters: 1, testament: "NT", words: 613 },
  { name: "Revelation", chapters: 22, testament: "NT", words: 11995 },
];

export const TOTAL_WORDS = BIBLE_BOOKS.reduce((acc, book) => acc + book.words, 0);
export const TOTAL_CHAPTERS = BIBLE_BOOKS.reduce((acc, book) => acc + book.chapters, 0);